// ============================================================================
// 互动地图 —— 内置美高默认地图包
// ----------------------------------------------------------------------------
// 结构与 JSON 导入的地图包完全一致；这里仅是把 JSON 写成 TS 模块常量以便内置。
// 如需完整字段说明请看 types.ts（MapPackSchema / MapLayerSchema / PinSchema）。
// ============================================================================
import type { MapPack } from './types';

export const defaultMapPack: MapPack = {
  name: '铁百合高中',
  version: '1.0.0',
  author: '番茄',
  // baseUrl 留空 —— 下方所有 image 都是完整外链（图床），不需要拼接前缀
  baseUrl: '',
  defaultMapId: 'overview',
  maps: {
    // ── 学院俯瞰图（根层级）──────────────────────────
    overview: {
      name: '学院俯瞰图',
      image: 'https://quantil.jsdelivr.net/gh/kayanorin/SillyTavernimg/美高模拟器/地图/学院俯瞰图.png',
      pins: [
        {
          id: 'central_stem',
          name: '中央剑径',
          x: 51.9,
          y: 63.5,
          desc: '权力与行政中心',
          color: '#e74c3c',
          type: 'portal',
          targetMapId: 'central_stem',
        },
        {
          id: 'iron_shield',
          name: '左翼·铁盾区',
          x: 36.5,
          y: 50.7,
          desc: '体育与体能训练区，"力量"的具象化，也是占地面积最大的女性主导区域。',
          color: '#3498db',
          type: 'portal',
          targetMapId: 'iron_shield',
        },
        {
          id: 'soft_petal',
          name: '右翼·柔瓣区',
          x: 69.4,
          y: 52.1,
          desc: '艺术文化中心，同时也是男生的主要活动区域。',
          color: '#e67e22',
          type: 'portal',
          targetMapId: 'soft_petal',
        },
        {
          id: 'dome_of_intellect',
          name: '冠部·智慧穹顶',
          x: 52.4,
          y: 19.6,
          desc: '学术与真理的圣殿。此区域拥有最密集的绿化，建筑完全被复杂的植物迷宫所环绕。',
          color: '#2ecc71',
          type: 'portal',
          targetMapId: 'dome_of_intellect',
        },
        {
          id: 'oasis',
          name: '独立绿洲',
          x: 89.9,
          y: 21.7,
          desc: '一个巨大的玻璃温室建筑，多功能生态栖息地。',
          color: '#1abc9c',
          type: 'building',
          floors: [
            { name: '多气候生态区', desc: '内部环境差异极大，例如热带雨林和温带花田' },
            { name: '生物与基因组实验室基地', desc: '由理工社主导的一处先进且受限制的实验区域' },
            { name: '珍稀植物园', desc: '培育用于为学生提炼顶级天然护肤精华油的珍贵异域植物' },
            { name: '玻璃屋咖啡馆', desc: '一处隐秘宁静的社交场所，仅供特权精英专享' },
          ],
        },
        {
          id: 'glory_gate',
          name: '荣光之门（南主门）',
          x: 52.4,
          y: 89.2,
          desc: '最为宏伟的礼仪主入口，用于重大集会和花车游行，直通铁百合广场。',
          color: '#f39c12',
          type: 'location',
        },
        {
          id: 'wisdom_gate',
          name: '智慧之门（北门）',
          x: 52.4,
          y: 6.9,
          desc: '充满学术氛围，是日间走读生和教职员工使用最频繁的日常入口。',
          color: '#f39c12',
          type: 'location',
        },
        {
          id: 'rose_gate',
          name: '玫瑰门（东侧门）',
          x: 79.8,
          y: 49.8,
          desc: '优雅的入口点，配备有防紫外线且防雨的连廊，直通软瓣区。',
          color: '#f39c12',
          type: 'location',
        },
        {
          id: 'iron_gate',
          name: '坚铁之门（西侧门）',
          x: 23.3,
          y: 48.1,
          desc: '气势恢宏且宽阔，是重型卡车和来访的校外运动队的专用通道，直通铁盾区。',
          color: '#f39c12',
          type: 'location',
        },
        {
          id: 'pin_mo4d5ct6f6',
          name: '女武神停车楼',
          x: 39.9,
          y: 66.8,
          desc: '一个拥有宽敞车位的室外多层停车综合体，适合女学生们驾驶的大型车辆。',
          color: '#5c5c5c',
          type: 'location',
        },
        {
          id: 'pin_mo4d6g6qxe',
          name: '温室落客区及地下车库',
          x: 76.9,
          y: 25.7,
          desc: '一个带顶棚的停车设施，配有通往软瓣区的有顶人行道。',
          color: '#f97676',
          type: 'location',
        },
      ],
    },

    // ── 中央剑径 ──────────────────────────────────────
    central_stem: {
      name: '中央剑径',
      image: 'https://quantil.jsdelivr.net/gh/kayanorin/SillyTavernimg/美高模拟器/地图/铁百合广场.png',
      parentMapId: 'overview',
      pins: [
        {
          id: 'plaza',
          name: '铁百合广场',
          x: 50.7,
          y: 69.7,
          desc: '大型集会空间，校园中心广场，铁百合剑雕塑矗立于此',
          color: '#e67e22',
          type: 'location',
        },
        {
          id: 'admin_tower',
          name: '中央行政塔楼',
          x: 43.4,
          y: 15.3,
          desc: '校园最高建筑，权力的象征。学生理事会总部也位于此处',
          color: '#9b59b6',
          type: 'portal',
          targetMapId: 'map_mo4dh288w8',
        },
        {
          id: 'glory_road',
          name: '荣光大道',
          x: 51,
          y: 97.9,
          desc: '连接铁百合广场与南主门的主干道，主要用于胜利游行与盛大庆典',
          color: '#f1c40f',
          type: 'location',
        },
      ],
    },

    // ── 左翼·铁盾区 ──────────────────────────────────
    iron_shield: {
      name: '左翼·铁盾区',
      image: 'https://quantil.jsdelivr.net/gh/kayanorin/SillyTavernimg/美高模拟器/地图/体育区.png',
      parentMapId: 'overview',
      pins: [
        {
          id: 'stadium',
          name: '铁百合体育场',
          x: 57.8,
          y: 35.4,
          desc: '大型户外体育场，橄榄球队主场',
          color: '#e74c3c',
          type: 'location',
        },
        {
          id: 'valkyrie_center',
          name: '女武神力量中心',
          x: 22,
          y: 32.9,
          desc: '致力于重塑女生肌肉与力量的顶级设施',
          color: '#e91e63',
          type: 'location',
        },
        {
          id: 'gym',
          name: '综合体育馆',
          x: 69.2,
          y: 79.2,
          desc: '承办各类室内运动与活动。',
          color: '#3498db',
          type: 'location',
        },
        {
          id: 'rehab',
          name: '运动医学与康复中心',
          x: 35.4,
          y: 25.2,
          desc: '提供最先进的物理康复与运动医学服务',
          color: '#2ecc71',
          type: 'location',
        },
        {
          id: 'team_camp',
          name: '校队专属训练营',
          x: 5.8,
          y: 25.7,
          desc: '由橄榄球队及其他竞技体育队伍独占使用的专属训练场地',
          color: '#f39c12',
          type: 'location',
        },
      ],
    },

    // ── 右翼·柔瓣区 ──────────────────────────────────
    soft_petal: {
      name: '右翼·柔瓣区',
      image: 'https://quantil.jsdelivr.net/gh/kayanorin/SillyTavernimg/美高模拟器/地图/文化区.png',
      parentMapId: 'overview',
      pins: [
        {
          id: 'apollo',
          name: '阿波罗美学中心',
          x: 48.4,
          y: 86.2,
          desc: '提供造型沙龙、仪态训练、时尚工作室等服务',
          color: '#e67e22',
          type: 'location',
        },
        {
          id: 'theater',
          name: '大剧院与艺术展厅',
          x: 49.9,
          y: 45.6,
          desc: '戏剧和艺术表演的主要场所',
          color: '#9b59b6',
          type: 'location',
        },
        {
          id: 'tea_terrace',
          name: '高端社交长廊与阳光午后茶台',
          x: 18.4,
          y: 74.8,
          desc: '风景优美、宁静祥和的社交场所，适合放松与交谈',
          color: '#f1c40f',
          type: 'location',
        },
        {
          id: 'pin_mo4e1hydtk',
          name: '玫瑰之门（东侧门）',
          x: 84.5,
          y: 79,
          desc: '东侧门，配备有防紫外线且防雨的连廊，直通软瓣区',
          color: '#f39c12',
          type: 'location',
        },
      ],
    },

    // ── 冠部·智慧穹顶 ────────────────────────────────
    dome_of_intellect: {
      name: '冠部·智慧穹顶',
      image: 'https://quantil.jsdelivr.net/gh/kayanorin/SillyTavernimg/美高模拟器/地图/教育区.png',
      parentMapId: 'overview',
      pins: [
        {
          id: 'teaching_complex',
          name: '精英教学综合体',
          x: 33.8,
          y: 57,
          desc: '进行标准课程与讲座的主要学术中心',
          color: '#3498db',
          type: 'location',
        },
        {
          id: 'stem_lab',
          name: '高级STEM实验室',
          x: 71.2,
          y: 57.8,
          desc: '配备最尖端的科学研究设备的实验楼',
          color: '#2ecc71',
          type: 'location',
        },
        {
          id: 'socrates_hall',
          name: '苏格拉底礼堂',
          x: 36.3,
          y: 27.5,
          desc: '一个用于大规模学术聚会和重要讲座的宏伟场所',
          color: '#9b59b6',
          type: 'location',
        },
        {
          id: 'botanical_maze',
          name: '植物迷宫',
          x: 18.5,
          y: 44.5,
          desc: '环绕建筑的复杂景观，象征着获取知识的曲折但回报丰厚的道路',
          color: '#1abc9c',
          type: 'location',
        },
        {
          id: 'cafeteria',
          name: '大食堂',
          x: 73.1,
          y: 27.9,
          desc: '一座位于高耸几何玻璃穹顶之下的宫殿式餐厅',
          color: '#e67e22',
          type: 'location',
        },
        {
          id: 'pin_mo4e2m39tk',
          name: '智慧之门（北门）',
          x: 52.8,
          y: 17.3,
          desc: '日间走读生和教职员工使用最频繁的日常入口',
          color: '#f39c12',
          type: 'location',
        },
      ],
    },

    // ── 中央行政塔楼内部（central_stem → admin_tower 传送目标）─
    map_mo4dh288w8: {
      name: '中央行政塔楼内部',
      image:
        'https://quantil.jsdelivr.net/gh/kayanorin/SillyTavernimg/美高模拟器/地图/中央行政塔楼与学生会总部-无字版.png',
      parentMapId: 'central_stem',
      pins: [
        {
          id: 'pin_mo4dipv2o4',
          name: 'B1: 服务器室',
          x: 25.4,
          y: 87.2,
          desc: '放置校园服务器的房间，空调常年运转保持较低温度',
          color: '#94c2ae',
          type: 'location',
        },
        {
          id: 'pin_mo4divquf3',
          name: 'B1: 杂物储藏室',
          x: 77.7,
          y: 88.3,
          desc: '存放备用制服组件、基础物资及失物招领物品。',
          color: '#94c2ae',
          type: 'location',
        },
        {
          id: 'pin_mo4dkhyvlg',
          name: '1F: 宏伟中庭',
          x: 46.6,
          y: 83.7,
          desc: '其中心矗立着一座微型"百合之剑"雕塑，基座牌匾上刻着校训："力量即优雅"',
          color: '#fffb85',
          type: 'location',
        },
        {
          id: 'pin_mo4dli8yvp',
          name: '2F: 教职员公共休息室',
          x: 25.8,
          y: 65.4,
          desc: '多个教职员工办公室。',
          color: '#ffc933',
          type: 'location',
        },
        {
          id: 'pin_mo4dmpeiid',
          name: '3F: 学生会总部',
          x: 68.3,
          y: 37.7,
          desc: '标有"议事厅"的巨大主会议室。',
          color: '#6b8e7f',
          type: 'location',
        },
        {
          id: 'pin_mo4doc7csi',
          name: '3F: 学生会会长套房',
          x: 78.8,
          y: 46.6,
          desc: '标有"议事厅"的巨大主会议室。',
          color: '#6b8e7f',
          type: 'location',
        },
        {
          id: 'pin_mo4dowylge',
          name: '4F: 战略理工实验室',
          x: 25.1,
          y: 42.9,
          desc: '一个专门用于研究和分析的区域',
          color: '#e6e6e6',
          type: 'location',
        },
        {
          id: 'pin_mo4dpvde9t',
          name: '5F: 瞭望尖塔',
          x: 35.4,
          y: 25.7,
          desc: '包括瞭望台和心理韧性迷宫',
          color: '#4e655b',
          type: 'location',
        },
      ],
    },
  },
};
