// ============================================================================
// 互动地图 —— 内置美高默认地图包
// ============================================================================
import type { MapPack } from './types';

const BASE_URL = 'https://testingcf.jsdelivr.net/gh/kayanorin/SillyTavernimg/美高模拟器/地图/';

export const defaultMapPack: MapPack = {
  name: '铁百合高中校园地图',
  version: '1.0.0',
  author: '番茄',
  baseUrl: BASE_URL,
  defaultMapId: 'overview',
  maps: {
    // ── 学院俯瞰图（根层级）──────────────────────────
    overview: {
      name: '学院俯瞰图',
      image: '学院俯瞰图.png',
      pins: [
        {
          id: 'central_stem',
          name: '中央剑径',
          x: 50,
          y: 45,
          desc: '权力与行政中心',
          color: '#e74c3c',
          type: 'portal',
          targetMapId: 'central_stem',
        },
        {
          id: 'iron_shield',
          name: '左翼·铁盾区',
          x: 20,
          y: 50,
          desc: '体育与体能训练区',
          color: '#3498db',
          type: 'portal',
          targetMapId: 'iron_shield',
        },
        {
          id: 'soft_petal',
          name: '右翼·柔瓣区',
          x: 80,
          y: 50,
          desc: '艺术与文化中心',
          color: '#e67e22',
          type: 'portal',
          targetMapId: 'soft_petal',
        },
        {
          id: 'dome_of_intellect',
          name: '冠部·智慧穹顶',
          x: 50,
          y: 18,
          desc: '学术研究圣殿',
          color: '#2ecc71',
          type: 'portal',
          targetMapId: 'dome_of_intellect',
        },
        {
          id: 'oasis',
          name: '独立绿洲',
          x: 75,
          y: 22,
          desc: '多功能生态玻璃温室',
          color: '#1abc9c',
          type: 'location',
        },
        {
          id: 'glory_gate',
          name: '荣光之门（南主门）',
          x: 50,
          y: 88,
          desc: '校园南侧主入口',
          color: '#f39c12',
          type: 'location',
        },
        {
          id: 'wisdom_gate',
          name: '智慧之门（北门）',
          x: 50,
          y: 5,
          desc: '校园北侧入口',
          color: '#f39c12',
          type: 'location',
        },
        {
          id: 'rose_gate',
          name: '玫瑰门（东侧门）',
          x: 95,
          y: 50,
          desc: '校园东侧门',
          color: '#f39c12',
          type: 'location',
        },
        {
          id: 'iron_gate',
          name: '铁门（西侧门）',
          x: 5,
          y: 50,
          desc: '校园西侧门',
          color: '#f39c12',
          type: 'location',
        },
      ],
    },

    // ── 中央剑径 ──────────────────────────────────────
    central_stem: {
      name: '中央剑径',
      image: '铁百合广场.png',
      parentMapId: 'overview',
      pins: [
        {
          id: 'plaza',
          name: '铁百合广场',
          x: 50,
          y: 60,
          desc: '校园中心广场，铁百合剑雕塑矗立于此',
          color: '#e67e22',
          type: 'location',
        },
        {
          id: 'admin_tower',
          name: '中央行政塔楼',
          x: 50,
          y: 30,
          desc: '校园最高建筑，权力的象征',
          color: '#9b59b6',
          type: 'building',
          floors: [
            { name: 'B1 - 服务器机房与储物间', desc: '地下层，存放着学校的核心服务器和大量储物柜' },
            { name: '1F - 大厅中庭', desc: '铁百合剑雕塑，大厅装饰华丽' },
            { name: '2F - 教职工办公区', desc: '教师办公室与会议室' },
            { name: '3F - 学生会总部', desc: '议事厅 / 主席套房' },
            { name: '4F - 战略STEM实验室', desc: '顶尖科技实验设备' },
            { name: '5F - 观察塔尖', desc: '观景台 / 心理韧性迷宫' },
          ],
        },
        {
          id: 'glory_road',
          name: '荣光大道',
          x: 50,
          y: 85,
          desc: '连接铁百合广场与南主门的主干道',
          color: '#f1c40f',
          type: 'location',
        },
      ],
    },

    // ── 左翼·铁盾区 ──────────────────────────────────
    iron_shield: {
      name: '左翼·铁盾区',
      image: '体育区.png',
      parentMapId: 'overview',
      pins: [
        {
          id: 'stadium',
          name: '铁百合体育场',
          x: 50,
          y: 30,
          desc: '大型户外体育场，橄榄球队主场',
          color: '#e74c3c',
          type: 'location',
        },
        {
          id: 'valkyrie_center',
          name: '女武神力量中心',
          x: 25,
          y: 55,
          desc: '女生专属力量训练设施',
          color: '#e91e63',
          type: 'location',
        },
        {
          id: 'gym',
          name: '综合体育馆',
          x: 75,
          y: 55,
          desc: '室内综合体育设施',
          color: '#3498db',
          type: 'location',
        },
        {
          id: 'rehab',
          name: '运动医学与康复中心',
          x: 40,
          y: 78,
          desc: '运动损伤治疗与康复训练',
          color: '#2ecc71',
          type: 'location',
        },
        {
          id: 'team_camp',
          name: '校队专属训练营',
          x: 65,
          y: 78,
          desc: '各校队的专属训练场地',
          color: '#f39c12',
          type: 'location',
        },
      ],
    },

    // ── 右翼·柔瓣区 ──────────────────────────────────
    soft_petal: {
      name: '右翼·柔瓣区',
      image: '文化区.png',
      parentMapId: 'overview',
      pins: [
        {
          id: 'apollo',
          name: '阿波罗美学中心',
          x: 50,
          y: 30,
          desc: '男生主要活动区域，美学与时尚',
          color: '#e67e22',
          type: 'location',
        },
        {
          id: 'theater',
          name: '大剧院与艺术展厅',
          x: 30,
          y: 55,
          desc: '戏剧演出与艺术展览',
          color: '#9b59b6',
          type: 'location',
        },
        {
          id: 'social_hall',
          name: '高端社交长廊',
          x: 70,
          y: 55,
          desc: '社交活动与派对场所',
          color: '#e91e63',
          type: 'location',
        },
        {
          id: 'tea_terrace',
          name: '阳光午后茶台',
          x: 50,
          y: 78,
          desc: '下午茶与休闲露台',
          color: '#f1c40f',
          type: 'location',
        },
      ],
    },

    // ── 冠部·智慧穹顶 ────────────────────────────────
    dome_of_intellect: {
      name: '冠部·智慧穹顶',
      image: '教育区.png',
      parentMapId: 'overview',
      pins: [
        {
          id: 'teaching_complex',
          name: '精英教学综合体',
          x: 50,
          y: 25,
          desc: '主教学楼群',
          color: '#3498db',
          type: 'location',
        },
        {
          id: 'stem_lab',
          name: '高级STEM实验室',
          x: 25,
          y: 50,
          desc: '顶尖科技实验设备',
          color: '#2ecc71',
          type: 'location',
        },
        {
          id: 'socrates_hall',
          name: '苏格拉底礼堂',
          x: 75,
          y: 50,
          desc: '大型学术报告厅',
          color: '#9b59b6',
          type: 'location',
        },
        {
          id: 'botanical_maze',
          name: '植物迷宫',
          x: 35,
          y: 75,
          desc: '精心设计的植物迷宫花园',
          color: '#1abc9c',
          type: 'location',
        },
        {
          id: 'cafeteria',
          name: '大食堂',
          x: 65,
          y: 75,
          desc: '校园主餐厅',
          color: '#e67e22',
          type: 'location',
        },
      ],
    },
  },
};
